#!/usr/bin/zsh

sudo x11vnc -norc -localhost -forever -shared -rfbauth /etc/init/x11vnc.pass -autoport 5900 -avahi -env X11VNC_AVAHI_NAME="Alpha" -desktop "Alpha's Remote Desktop" -repeat -bg -o /var/log/x11vnc.log
